services:
  db:
    image: postgres:16
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    
  app:
    build: .
    container_name: system_management_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file: .env

volumes:
  db_data: